version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: aftas_db
    ports:
      - "3306:3306"

  aftasbackend:
    build:
      context: ./competition-management-back
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aftas_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  frontend:
    build:
      context: ./competition-management
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - aftasbackend